package main

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"

	"github.com/adrg/xdg"
	"github.com/sewnie/wine"
	"github.com/vinegarhq/vinegar/internal/dirs"
	"golang.org/x/sys/unix"
)

// Wine installs a seccomp filter onto its processes, which is inherited by
// every Unix program spawned by Wine, such as the web browser launched by
// winebrowser (winebrowser → xdg-open → ... → browser). Browsers such as
// Chromium are killed by that filter (SIGSYS), making browser login and
// links opened by Studio fail.
//
// Instead, winebrowser is configured to run a helper which only hands the
// URL to Vinegar through a FIFO, and Vinegar opens it with xdg-open outside
// of Wine's process tree, leaving the browser and its own sandbox intact.
//
// URLs may contain authentication tokens, and are never logged.

var (
	browserFIFO    = filepath.Join(xdg.RuntimeDir, "vinegar-browser")
	browserHelper  = filepath.Join(dirs.Data, "winebrowser-helper")
	browserRegPath = `HKCU\Software\Wine\WineBrowser`
)

// The helper falls back to xdg-open if Vinegar is not running, and
// otherwise writes the URL as a single NUL-terminated message, which never
// blocks as Vinegar keeps the FIFO open for as long as it runs.
const browserHelperScript = `#!/bin/sh
# Generated by Vinegar. Hands the URL given by winebrowser over to Vinegar,
# which opens it outside of Wine's process tree.
fifo=%s
if [ ! -p "$fifo" ] || ! kill -0 %d 2>/dev/null; then
	exec xdg-open "$@"
fi
printf '%%s\0' "$1" > "$fifo"
`

// browserCommand is the value of winebrowser's Browsers registry value,
// a comma-separated list of commands, each parsed as a command line.
func browserCommand() string {
	helper := browserHelper
	if strings.ContainsAny(helper, " \t") {
		helper = `"` + helper + `"`
	}
	return helper + ",xdg-open"
}

// serveBrowser writes the winebrowser helper and serves URLs opened within
// Wine, until the FIFO is closed.
func serveBrowser() (io.Closer, error) {
	if err := os.MkdirAll(dirs.Data, 0o755); err != nil {
		return nil, err
	}
	script := fmt.Sprintf(browserHelperScript, shellQuote(browserFIFO), os.Getpid())
	if err := os.WriteFile(browserHelper, []byte(script), 0o755); err != nil {
		return nil, fmt.Errorf("helper: %w", err)
	}
	if err := os.Chmod(browserHelper, 0o755); err != nil {
		return nil, fmt.Errorf("helper: %w", err)
	}

	if err := os.Remove(browserFIFO); err != nil && !errors.Is(err, os.ErrNotExist) {
		return nil, fmt.Errorf("fifo: %w", err)
	}
	if err := unix.Mkfifo(browserFIFO, 0o600); err != nil {
		return nil, fmt.Errorf("fifo: %w", err)
	}

	// Opened for writing as well, so that reading never reaches EOF
	// once a helper is done writing, and helpers never block.
	f, err := os.OpenFile(browserFIFO, os.O_RDWR, 0)
	if err != nil {
		os.Remove(browserFIFO)
		return nil, fmt.Errorf("fifo: %w", err)
	}

	go func() {
		r := bufio.NewReader(f)
		for {
			msg, err := r.ReadString(0)
			if err != nil {
				if !errors.Is(err, os.ErrClosed) {
					slog.Error("Failed to read URL from Wine", "err", err)
				}
				return
			}
			if uri := strings.TrimSuffix(msg, "\x00"); uri != "" {
				openFromWine(uri)
			}
		}
	}()

	slog.Info("Serving URLs opened within Wine", "helper", browserHelper)
	return browserServer{f}, nil
}

type browserServer struct{ *os.File }

func (s browserServer) Close() error {
	os.Remove(browserFIFO)
	return s.File.Close()
}

// openFromWine opens the given URL, or Unix path given by winebrowser for
// file URLs, with the user's default application for it.
func openFromWine(uri string) {
	log := slog.With("url", redactURL(uri))
	log.Info("Opening URL from Wine")

	cmd := exec.Command("xdg-open", uri)
	if err := cmd.Start(); err != nil {
		log.Error("Failed to open URL from Wine", "err", err)
		return
	}
	go func() {
		if err := cmd.Wait(); err != nil {
			log.Error("Failed to open URL from Wine", "err", err)
		}
	}()
}

// redactURL returns only the scheme and host of the given URL,
// as the rest of it may contain secrets such as authentication tokens.
func redactURL(uri string) string {
	if filepath.IsAbs(uri) {
		return "<path>"
	}
	u, err := url.Parse(uri)
	if err != nil || u.Scheme == "" {
		return "<invalid>"
	}
	if u.Host == "" {
		return u.Scheme + ":<redacted>"
	}
	return u.Scheme + "://" + u.Host + "/<redacted>"
}

// redactArgs returns the given command arguments with Roblox URIs,
// which may contain authentication tokens, redacted.
func redactArgs(args []string) []string {
	args = slices.Clone(args)
	for i, arg := range args {
		if strings.HasPrefix(arg, "roblox-studio:") || strings.HasPrefix(arg, authScheme) {
			args[i] = redactURL(arg)
		}
	}
	return args
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// setWineBrowser configures winebrowser in the Wineprefix to use
// Vinegar's helper, if not already configured.
func (a *app) setWineBrowser(offline *wine.Registry) error {
	if offline != nil {
		if k := offline.Query(browserRegPath); k != nil {
			if v := k.GetValue("Browsers"); v != nil && v.Data == browserCommand() {
				return nil
			}
		}
	}

	slog.Info("Setting Wine browser to Vinegar's helper")
	return a.pfx.RegistryAdd(browserRegPath, "Browsers", browserCommand())
}
