package main

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"

	"github.com/adrg/xdg"
	"github.com/sewnie/wine"
	"github.com/vinegarhq/vinegar/internal/dirs"
	"github.com/vinegarhq/vinegar/internal/gutil"
	"golang.org/x/sys/unix"
)

// Wine installs a seccomp filter onto its processes, which is inherited by
// every Unix program spawned by Wine, such as the web browser launched by
// winebrowser (winebrowser → xdg-open → ... → browser). Browsers such as
// Chromium are killed by that filter (SIGSYS), making browser login and
// links opened by Studio fail.
//
// Instead, winebrowser is configured to run a helper which only hands the
// URL to Vinegar through a FIFO, and Vinegar opens it with xdg-open outside
// of Wine's process tree, leaving the browser and its own sandbox intact.
//
// URLs may contain authentication tokens, and are never logged.

var (
	browserFIFO    = filepath.Join(xdg.RuntimeDir, "vinegar-browser")
	browserHelper  = filepath.Join(dirs.Data, "winebrowser-helper")
	browserRegPath = `HKCU\Software\Wine\WineBrowser`
)

// The helper writes the URL as a single NUL-terminated message, which does
// not block while Vinegar runs, as Vinegar keeps the FIFO open. It falls back
// to xdg-open if Vinegar is not running, identified by both its PID and its
// start time (as a PID may be reused), or if writing does not finish in time.
//
// The FIFO is never removed, only atomically replaced, so that writing to it
// can never create a regular file containing the URL instead.
const browserHelperScript = `#!/bin/sh
# Generated by Vinegar. Hands the URL given by winebrowser over to Vinegar,
# which opens it outside of Wine's process tree.
fifo=%s

running() {
	{ read -r stat < /proc/%d/stat; } 2>/dev/null || return 1
	set -- ${stat##*') '}
	[ "${20}" = %s ]
}

t=
command -v timeout >/dev/null 2>&1 && t='timeout 5'
if [ -p "$fifo" ] && running &&
	$t sh -c 'printf "%%s\0" "$2" > "$1"' sh "$fifo" "$1" 2>/dev/null; then
	exit 0
fi
exec xdg-open "$@"
`

// startTime returns the start time of the current process, as given by
// field 22 of /proc/self/stat.
func startTime() (string, error) {
	b, err := os.ReadFile("/proc/self/stat")
	if err != nil {
		return "", err
	}
	// The process name (field 2) is parenthesized and may contain spaces.
	i := strings.LastIndexByte(string(b), ')')
	if i < 0 {
		return "", errors.New("malformed stat")
	}
	f := strings.Fields(string(b[i+1:]))
	if len(f) < 20 {
		return "", errors.New("malformed stat")
	}
	return f[19], nil
}

// browserCommand is the value of winebrowser's Browsers registry value,
// a comma-separated list of commands, each parsed as a command line.
func browserCommand() string {
	helper := browserHelper
	if strings.ContainsAny(helper, " \t") {
		helper = `"` + helper + `"`
	}
	return helper + ",xdg-open"
}

// serveBrowser writes the winebrowser helper and serves URLs opened within
// Wine, until the FIFO is closed.
func (a *app) serveBrowser() (io.Closer, error) {
	start, err := startTime()
	if err != nil {
		return nil, fmt.Errorf("start time: %w", err)
	}

	// Replace any previous FIFO (or a regular file) atomically, so
	// that the path always exists for helpers.
	tmp := browserFIFO + ".new"
	if err := os.Remove(tmp); err != nil && !errors.Is(err, os.ErrNotExist) {
		return nil, fmt.Errorf("fifo: %w", err)
	}
	if err := unix.Mkfifo(tmp, 0o600); err != nil {
		return nil, fmt.Errorf("fifo: %w", err)
	}
	// Opened for writing as well, so that reading never reaches EOF
	// once a helper is done writing, and helpers never block.
	f, err := os.OpenFile(tmp, os.O_RDWR, 0)
	if err != nil {
		os.Remove(tmp)
		return nil, fmt.Errorf("fifo: %w", err)
	}
	if err := os.Rename(tmp, browserFIFO); err != nil {
		f.Close()
		os.Remove(tmp)
		return nil, fmt.Errorf("fifo: %w", err)
	}

	if err := os.MkdirAll(dirs.Data, 0o755); err != nil {
		f.Close()
		return nil, err
	}
	script := fmt.Sprintf(browserHelperScript,
		shellQuote(browserFIFO), os.Getpid(), shellQuote(start))
	if err := os.WriteFile(browserHelper, []byte(script), 0o755); err == nil {
		err = os.Chmod(browserHelper, 0o755)
	}
	if err != nil {
		f.Close()
		return nil, fmt.Errorf("helper: %w", err)
	}

	go func() {
		r := bufio.NewReader(f)
		for {
			msg, err := r.ReadString(0)
			if err != nil {
				if !errors.Is(err, os.ErrClosed) {
					slog.Error("Failed to read URL from Wine", "err", err)
				}
				return
			}
			if uri := strings.TrimSuffix(msg, "\x00"); uri != "" {
				a.openFromWine(uri)
			}
		}
	}()

	slog.Info("Serving URLs opened within Wine", "helper", browserHelper)

	// The FIFO is deliberately left in place once closed, see
	// browserHelperScript.
	return f, nil
}

// openFromWine opens the given URL, or Unix path given by winebrowser for
// file URLs, with the user's default application for it.
func (a *app) openFromWine(uri string) {
	log := slog.With("url", redactURL(uri))
	log.Info("Opening URL from Wine")

	if isStudioLogin(uri) {
		gutil.IdleAdd(a.boot.promptLogin)
	}

	cmd := exec.Command("xdg-open", uri)
	if err := cmd.Start(); err != nil {
		log.Error("Failed to open URL from Wine", "err", err)
		return
	}
	go func() {
		if err := cmd.Wait(); err != nil {
			log.Error("Failed to open URL from Wine", "err", err)
		}
	}()
}

// isStudioLogin reports whether the given URL is Studio's sign in page,
// which redirects to a roblox-studio-auth URI once signed in.
func isStudioLogin(uri string) bool {
	u, err := url.Parse(uri)
	if err != nil || (u.Scheme != "https" && u.Scheme != "http") ||
		(u.Hostname() != "roblox.com" && !strings.HasSuffix(u.Hostname(), ".roblox.com")) {
		return false
	}

	// The redirect URI may be nested within other URL parameters.
	s := u.RawQuery
	for range 3 {
		if strings.Contains(strings.ToLower(s), authScheme) {
			return true
		}
		if s, err = url.QueryUnescape(s); err != nil {
			return false
		}
	}
	return strings.Contains(strings.ToLower(s), authScheme)
}

// redactURL returns only the scheme of the given URL, and its host for
// HTTP(S) URLs, as the rest of it may contain secrets such as
// authentication tokens. For other schemes, even the authority
// (roblox-studio-auth://...) may be a secret.
func redactURL(uri string) string {
	if filepath.IsAbs(uri) {
		return "<path>"
	}
	u, err := url.Parse(uri)
	if err != nil || u.Scheme == "" {
		return "<invalid>"
	}
	// Scheme is always lowercase, the host of an URL excludes user info.
	if (u.Scheme == "https" || u.Scheme == "http") && u.Host != "" {
		return u.Scheme + "://" + u.Host + "/<redacted>"
	}
	return u.Scheme + ":<redacted>"
}

// redactArgs returns the given command arguments with Roblox URIs,
// which may contain authentication tokens, redacted.
func redactArgs(args []string) []string {
	args = slices.Clone(args)
	for i, arg := range args {
		lower := strings.ToLower(arg)
		if strings.Contains(lower, "roblox-studio") || strings.Contains(lower, "roblox-player") {
			args[i] = redactURL(strings.TrimSpace(arg))
		}
	}
	return args
}

// isAuthURI reports whether the given string is a roblox-studio-auth URI,
// of which the scheme is case-insensitive.
func isAuthURI(s string) bool {
	return strings.HasPrefix(strings.ToLower(strings.TrimSpace(s)), authScheme)
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// setWineBrowser configures winebrowser in the Wineprefix to use
// Vinegar's helper, if not already configured.
func (a *app) setWineBrowser(offline *wine.Registry) error {
	if offline != nil {
		if k := offline.Query(browserRegPath); k != nil {
			if v := k.GetValue("Browsers"); v != nil && v.Data == browserCommand() {
				return nil
			}
		}
	}

	slog.Info("Setting Wine browser to Vinegar's helper")
	return a.pfx.RegistryAdd(browserRegPath, "Browsers", browserCommand())
}
